### ISSUE TITLE
Compare Raleigh ETJ Boundary with Census Tracts

### ISSUE THREAD

**Issue by adamajm** [CORaleigh/affordable_rental_tracking#17]
Find out which census tracts are not fully inside the Raleigh ETJ boundary so we can understand how to benchmark our results against Census estimates

**Comment by adamajm** [comment]
ETJ: http://data.ral.opendata.arcgis.com/datasets/9d163c53a6884459a07b8b10e18e8839_0

**Comment by adamajm** [comment]
I looked at this on arcgis desktop: found some clear cases of census tracts that BARELY overlap with Raleigh jurisdiction, therefore would not be useful to compare our Rental Unit numbers with. They are:
053009
052802
052803
053003

We should exclude these census tracts from any comparative analysis (until Raleigh annexes those territories!).

**Comment by moor1204** [comment]
Thanks Adam!
