### ISSUE TITLE
Research Zillow rent estimate methodologies and available data

### ISSUE THREAD

**Issue by mmspencer** [CORaleigh/affordable_rental_tracking#6]
What data/methods can we get from Zillow or other real estate and rental listing sites to determine the cost of each rental?

**Comment by mmspencer** [comment]
http://www.zillow.com/research/data/
http://www.zillow.com/research/zillow-rent-index-methodology-2393/

**Comment by adamajm** [comment]
API for Zillow Rent Estimate includes: 
Rent Zestimate (in $)
Last updated
30-day (in $)
Valuation range (high) (in $)
Valuation range (low) (in $)

**Comment by adamajm** [comment]
http://www.zillow.com/howto/api/APIOverview.htm

**Comment by adamajm** [comment]
http://www.zillow.com/howto/api/GetZestimate.htm

**Comment by mmspencer** [comment]
GetSearchResults returns same information (including rent zestimate) as GetZestimate, but by searching with an address rather than a zpid.
http://www.zillow.com/howto/api/GetSearchResults.htm

**Comment by agurdian** [comment]
use PHP: HttpRequest to build a query and save the results http://php.net/manual/en/class.httprequest.php

**Comment by mmspencer** [comment]
Sample Zillow API command line: http://www.zillow.com/webservice/GetSearchResults.htm?zws-id=<ZWSID>&address=2114+Bigelow+Ave&citystatezip=Seattle%2C+WA
